name: Talbotiq
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  readmore: ^2.2.0
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^20.4.43
  timelines: ^0.1.0
  introduction_screen: ^3.1.4
  pin_code_fields: ^7.4.0
  flutter_rating_bar: ^4.0.1
  timeline_tile: ^2.0.0
  card_swiper: ^2.0.4
  flutter_switch: ^0.3.2
  html_editor_enhanced: ^2.5.1
  flutter_quill: ^2.0.7

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/image/

